name:                haskell-aoc
version:             0.1.0.0
github:              "rolandtritsch/haskell-aoc-2018"
license:             BSD3
author:              "Roland Tritsch"
maintainer:          "roland@tritsch.org"
copyright:           "2018 Roland Tritsch"

extra-source-files:
- README.md

synopsis:            An implementation of the Advent of Code - 2018
category:            Web

description:         Please see the README on Github

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
  - src
  ghc-options:
  - -O2
  - -Wall -Werror
  dependencies:
  - containers
  - split
  - array
  - vector
  - safe

executables:
  haskell-aoc-exe:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -main-is Main.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers
    - Unique

  haskell-aoc-day00p1:
    main: app/Day00/Part1.hs
    ghc-options:
    - -main-is Day00.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day00p2:
    main: app/Day00/Part2.hs
    ghc-options:
    - -main-is Day00.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day01p1:
    main: app/Day01/Part1.hs
    ghc-options:
    - -main-is Day01.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day01p2:
    main: app/Day01/Part2.hs
    ghc-options:
    - -main-is Day01.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers

  haskell-aoc-day02p1:
    main: app/Day02/Part1.hs
    ghc-options:
    - -main-is Day02.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - Unique

  haskell-aoc-day02p2:
    main: app/Day02/Part2.hs
    ghc-options:
    - -main-is Day02.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day03p1:
    main: app/Day03/Part1.hs
    ghc-options:
    - -main-is Day03.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers

  haskell-aoc-day03p2:
    main: app/Day03/Part2.hs
    ghc-options:
    - -main-is Day03.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers

  haskell-aoc-day04p1:
    main: app/Day04/Part1.hs
    ghc-options:
    - -main-is Day04.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day04p2:
    main: app/Day04/Part2.hs
    ghc-options:
    - -main-is Day04.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day05p1:
    main: app/Day05/Part1.hs
    ghc-options:
    - -main-is Day05.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day05p2:
    main: app/Day05/Part2.hs
    ghc-options:
    - -main-is Day05.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day06p1:
    main: app/Day06/Part1.hs
    ghc-options:
    - -main-is Day06.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day06p2:
    main: app/Day06/Part2.hs
    ghc-options:
    - -main-is Day06.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers

  haskell-aoc-day07p1:
    main: app/Day07/Part1.hs
    ghc-options:
    - -main-is Day07.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day07p2:
    main: app/Day07/Part2.hs
    ghc-options:
    - -main-is Day07.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day08p1:
    main: app/Day08/Part1.hs
    ghc-options:
    - -main-is Day08.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day08p2:
    main: app/Day08/Part2.hs
    ghc-options:
    - -main-is Day08.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers

  haskell-aoc-day09p1:
    main: app/Day00/Part1.hs
    ghc-options:
    - -main-is Day00.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day09p2:
    main: app/Day00/Part2.hs
    ghc-options:
    - -main-is Day00.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day10p1:
    main: app/Day10/Part1.hs
    ghc-options:
    - -main-is Day10.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day10p2:
    main: app/Day10/Part2.hs
    ghc-options:
    - -main-is Day10.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day11p1:
    main: app/Day11/Part1.hs
    ghc-options:
    - -main-is Day11.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day11p2:
    main: app/Day11/Part2.hs
    ghc-options:
    - -main-is Day11.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day12p1:
    main: app/Day12/Part1.hs
    ghc-options:
    - -main-is Day12.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day12p2:
    main: app/Day12/Part2.hs
    ghc-options:
    - -main-is Day12.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day13p1:
    main: app/Day13/Part1.hs
    ghc-options:
    - -main-is Day13.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers

  haskell-aoc-day13p2:
    main: app/Day13/Part2.hs
    ghc-options:
    - -main-is Day13.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers

  haskell-aoc-day14p1:
    main: app/Day14/Part1.hs
    ghc-options:
    - -main-is Day14.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day14p2:
    main: app/Day14/Part2.hs
    ghc-options:
    - -main-is Day14.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day15p1:
    main: app/Day15/Part1.hs
    ghc-options:
    - -main-is Day15.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day15p2:
    main: app/Day15/Part2.hs
    ghc-options:
    - -main-is Day15.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

tests:
  haskell-aoc-test:
    main: Spec.hs
    source-dirs:
    - test
    - app
    ghc-options:
    - -main-is Spec.main
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers
    - Unique

  haskell-aoc-test-day00:
    main: Day00Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day00.Part1
    - Day00.Part2
    ghc-options:
    - -main-is Day00Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit

  haskell-aoc-test-day01:
    main: Day01Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day01.Part1
    - Day01.Part2
    ghc-options:
    - -main-is Day01Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers

  haskell-aoc-test-day02:
    main: Day02Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day02.Part1
    - Day02.Part2
    ghc-options:
    - -main-is Day02Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - Unique

  haskell-aoc-test-day03:
    main: Day03Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day03.Part1
    - Day03.Part2
    ghc-options:
    - -main-is Day03Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers

  haskell-aoc-test-day04:
    main: Day04Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day04.Part1
    - Day04.Part2
    ghc-options:
    - -main-is Day04Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit

  haskell-aoc-test-day05:
    main: Day05Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day05.Part1
    - Day05.Part2
    ghc-options:
    - -main-is Day05Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit

  haskell-aoc-test-day06:
    main: Day06Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day06.Part1
    - Day06.Part2
    ghc-options:
    - -main-is Day06Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers

  haskell-aoc-test-day07:
    main: Day07Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day07.Part1
    - Day07.Part2
    ghc-options:
    - -main-is Day07Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit

  haskell-aoc-test-day08:
    main: Day08Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day08.Part1
    - Day08.Part2
    ghc-options:
    - -main-is Day08Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers

  haskell-aoc-test-day09:
    main: Day09Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day09.Part1
    - Day09.Part2
    ghc-options:
    - -main-is Day09Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers

  haskell-aoc-test-day10:
    main: Day10Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day10.Part1
    - Day10.Part2
    ghc-options:
    - -main-is Day10Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit

  haskell-aoc-test-day11:
    main: Day11Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day11.Part1
    - Day11.Part2
    ghc-options:
    - -main-is Day11Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers

  haskell-aoc-test-day12:
    main: Day12Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day12.Part1
    - Day12.Part2
    ghc-options:
    - -main-is Day12Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers

  haskell-aoc-test-day13:
    main: Day13Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day13.Part1
    - Day13.Part2
    ghc-options:
    - -main-is Day13Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers

  haskell-aoc-test-day14:
    main: Day14Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day14.Part1
    - Day14.Part2
    ghc-options:
    - -main-is Day14Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit

  haskell-aoc-test-day15:
    main: Day15Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day15.Part1
    - Day15.Part2
    ghc-options:
    - -main-is Day15Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers
