name:                haskell-aoc
version:             0.1.0.0
github:              "rolandtritsch/haskell-aoc-2018"
license:             BSD3
author:              "Roland Tritsch"
maintainer:          "roland@tritsch.org"
copyright:           "2018 Roland Tritsch"

extra-source-files:
- README.md

synopsis:            An implementation of the Advent of Code - 2018
category:            Web

description:         Please see the README on Github

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:
  - src
  ghc-options:
  - -O2
  - -Wall -Werror
  dependencies:
  - containers
  - split

executables:
  haskell-aoc-exe:
    main: Main.hs
    source-dirs:
    - app
    ghc-options:
    - -main-is Main.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers
    - Unique

  haskell-aoc-day00p1:
    main: app/Day00/Part1.hs
    ghc-options:
    - -main-is Day00.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day00p2:
    main: app/Day00/Part2.hs
    ghc-options:
    - -main-is Day00.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day01p1:
    main: app/Day01/Part1.hs
    ghc-options:
    - -main-is Day01.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day01p2:
    main: app/Day01/Part2.hs
    ghc-options:
    - -main-is Day01.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers

  haskell-aoc-day02p1:
    main: app/Day02/Part1.hs
    ghc-options:
    - -main-is Day02.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - Unique

  haskell-aoc-day02p2:
    main: app/Day02/Part2.hs
    ghc-options:
    - -main-is Day02.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day03p1:
    main: app/Day03/Part1.hs
    ghc-options:
    - -main-is Day03.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers

  haskell-aoc-day03p2:
    main: app/Day03/Part2.hs
    ghc-options:
    - -main-is Day03.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers

  haskell-aoc-day04p1:
    main: app/Day04/Part1.hs
    ghc-options:
    - -main-is Day04.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day04p2:
    main: app/Day04/Part2.hs
    ghc-options:
    - -main-is Day04.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day05p1:
    main: app/Day05/Part1.hs
    ghc-options:
    - -main-is Day05.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day05p2:
    main: app/Day05/Part2.hs
    ghc-options:
    - -main-is Day05.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day06p1:
    main: app/Day06/Part1.hs
    ghc-options:
    - -main-is Day06.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day06p2:
    main: app/Day06/Part2.hs
    ghc-options:
    - -main-is Day06.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit
    - containers

  haskell-aoc-day07p1:
    main: app/Day07/Part1.hs
    ghc-options:
    - -main-is Day07.Part1.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

  haskell-aoc-day07p2:
    main: app/Day07/Part2.hs
    ghc-options:
    - -main-is Day07.Part2.main
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - timeit

tests:
  haskell-aoc-test:
    main: Spec.hs
    source-dirs:
    - test
    - app
    ghc-options:
    - -main-is Spec.main
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers
    - Unique

  haskell-aoc-test-day00:
    main: Day00Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day00.Part1
    - Day00.Part2
    ghc-options:
    - -main-is Day00Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit

  haskell-aoc-test-day01:
    main: Day01Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day01.Part1
    - Day01.Part2
    ghc-options:
    - -main-is Day01Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers

  haskell-aoc-test-day02:
    main: Day02Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day02.Part1
    - Day02.Part2
    ghc-options:
    - -main-is Day02Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - Unique

  haskell-aoc-test-day03:
    main: Day03Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day03.Part1
    - Day03.Part2
    ghc-options:
    - -main-is Day03Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers

  haskell-aoc-test-day04:
    main: Day04Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day04.Part1
    - Day04.Part2
    ghc-options:
    - -main-is Day04Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit

  haskell-aoc-test-day05:
    main: Day05Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day05.Part1
    - Day05.Part2
    ghc-options:
    - -main-is Day05Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit

  haskell-aoc-test-day06:
    main: Day06Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day06.Part1
    - Day06.Part2
    ghc-options:
    - -main-is Day06Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
    - containers

  haskell-aoc-test-day07:
    main: Day07Spec.hs
    source-dirs:
    - test
    - app
    other-modules:
    - Day07.Part1
    - Day07.Part2
    ghc-options:
    - -main-is Day07Spec.run
    - -O2 -threaded
    - -Wall -Werror
    dependencies:
    - haskell-aoc
    - hspec
    - timeit
