# The resolver to use. Downgraded to 12.14 (to make intero work (again)).
#resolver: lts-12.24
resolver: lts-12.14

# User packages to be built.
packages:
- .

# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps:
- Unique-0.4.7.5
- megaparsec-7.0.4
- hspec-megaparsec-2.0.0
