version: 2.1
jobs:
  build-haskell:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-haskell-aoc-2018-v1-{{ checksum "package.yaml" }}
      - run:
          name: Resolve/Update Dependencies
          command: stack setup
      - run:
          name: Run tests
          command: stack test
          no_output_timeout: 60m
      - run:
          name: Run exe
          command: stack build :haskell-aoc-exe --exec haskell-aoc-exe
          no_output_timeout: 60m
      - run:
          name: Install executable
          command: stack install
      - save_cache:
          name: Cache Dependencies
          key: cci-haskell-aoc-2018-v1-{{ checksum "package.yaml" }}
          paths:
            - ~/.stack
            - ~/.stack-work
      - store_artifacts:
          path: ~/.local/bin/haskell-aoc-exe
          destination: haskell-aoc-exe

  build-eta:
    docker:
      - image: typelead/eta:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-eta-aoc-2018-v1-{{ checksum "package.yaml" }}
      - run:
          name: Init build
          command: etlas update && etlas select latest
      - run:
          name: Run build
          command: etlas build --enable-tests
      - run:
          name: Run exe
          command: export ETA_JAVA_ARGS="-Xss1024M -Xmx4096M" && etlas run haskell-aoc-exe
          no_output_timeout: 120m
      - save_cache:
          name: Save Cache Dependencies
          key: cci-eta-aoc-2018-v1-{{ checksum "package.yaml" }}
          paths:
            - ~/.etlas
            - ~/.eta
            - ~/dist

workflows:
  version: 2
  full_cycle:
    jobs:
      - build-haskell
      - build-eta
